export enum ActionTypes {
    'SET_TASKS' = 'SET_TASKS',
    'SET_USERS' = 'SET_USERS',
    'EDIT_TASK' = 'EDIT_TASK',
    'SET_STATUSES' = 'GET_STATUSES',
    'SET_PRIORITIES' = 'GET_PRIORITIES',
    'GET_TASK_BY_ID' = 'GET_TASK_BY_ID',
    'SET_TENANTS_KEY' = 'SET_TENANTS_KEY',
    'SET_SELECTED_TASK' = 'SET_SELECTED_TASK',
    'GET_REQUESTS_DATA' = 'GET_REQUESTS_DATA',
    'ADD_NEW_REQUEST_DATA' = 'ADD_NEW_REQUEST_DATA',
}